### ISSUE TITLE
Text displays as white in the visual editor

### ISSUE THREAD

**Issue by ablevesque** [NEU-DSG/toolkit_requests#74] opened 2017-02-01 19:31 UTC
I can't replicate the problem to get a screenshot, but occasionally in the visual editor in page builder, text that is put in the text box shows up as white, making it look like nothing is being typed. Issue was showing up on toolkittraining.dsg.northeastern.edu.

I'm going to work on trying to replicate the issue.

**Comment by elizoller** [comment] 2017-02-01 19:32
Ok, thanks

**Comment by ablevesque** [comment] 2017-02-01 19:52
I can't get it to replicate in chrome at all, but Kaley says she's had the problem on and off for awhile, so she might have more information.

**Comment by sarahjeansweeney** [comment] 2017-10-12 18:51
Closing because duplicate of #76, which has more description.

**Closed by sarahjeansweeney** 2017-10-12 18:51 UTC
