### ISSUE TITLE
SiteOrigin Hero Image overlays the Side Menu

### ISSUE THREAD

**Issue by mbarney17** [NEU-DSG/toolkit_requests#116] opened 2018-10-09 13:50 UTC
When using SiteOrigin Hero widgets for headers that span the page, the side menu does not move or accomodate the design.

<img width="1440" alt="screen shot 2018-09-27 at 3 33 42 pm" src="https://user-images.githubusercontent.com/35934061/46673769-88828700-cba8-11e8-981f-780fbb2dbe5b.png">

This was attemped on the Early Caribbean Digital Archive CERES installation on MacBook Pro with Chrome (Version 69.0.3497.100)

**Comment by patrickmj** [comment] 2018-10-09 16:07
Not sure how close this will get to the desired effect, but when I reproduced this locally adding this CSS seemed to make progress:
```
#secondary {
	z-index: 500;
	position: relative;
	right: -200px;
	top: 100px;
}

.sow-slider-image-cover {
    background-image: unset;
}

```
The right and top values probably need tweaking for where exactly you want the menu to appear.

The unset on the background image thing probably needs some extra attention. It gets around the awkward requirement of using an image, but it might apply too broadly. It looks like adding classes to the elements via the interface could do the job of making it more specific. Then, on the same element you could style whatever color you want.
Hope that helps.

**Comment by AmandaRust** [comment] 2019-08-08 14:00
I'm going to work w/ Alanna to see if this is still an issue. I'm hoping that if she does those banner images a different way, it might change things. If not, I think it's OK to just say this is a known bug.

**Closed by AmandaRust** 2019-08-08 14:00 UTC
